#pragma once

namespace —ñ‹“ {
	namespace ‰Æ•ó {

		namespace ‰Æ•ó•ª—Ş {
			const int ’ƒ˜q = 0x0;
			const int ’ƒšâ = 0x1;
			const int ’ƒ“ü = 0x2;
			const int ’ƒŠ˜ = 0x3;
			const int ‰Ô“ü = 0x4;
			const int “Œ• = 0x5;
			const int ‘„ = 0x6;
			const int ‹ï‘« = 0x7;
			const int ”n = 0x8;
			const int ˆÆ = 0x9;
			const int w‰HD = 0xA;
			const int Šªq–{ = 0xB;
			const int –¾’©’Ô–{ = 0xC;
			const int –Ø = 0xD;
			const int ’n‹…‹V = 0xE;
			const int “ì”ØŒv = 0xF;
			const int …–n‰æ = 0x10;
			const int \š‰Ë = 0x11;
			const int ¹‘ = 0x12;
			const int ‹Êè”  = 0x13;
			const int ƒr[ƒhƒ”t = 0x14;
			const int ‰“Šá‹¾ = 0x15;
			const int ƒ‹ƒ\ƒ“šâ = 0x16;
			const int ‰Œ‘ = 0x17;
		};

		namespace ‰Æ•ó‰æ‘œ {
			const int ’ƒ˜q = 0x0;
			const int ’ƒšâ = 0x1;
			const int ’ƒ“ü = 0x2;
			const int ’ƒŠ˜ = 0x3;
			const int ‰Ô“ü = 0x4;
			const int “Œ• = 0x5;
			const int ‘„ = 0x6;
			const int ‹ï‘« = 0x7;
			const int ”n = 0x8;
			const int ˆÆ = 0x9;
			const int w‰HD = 0xA;
			const int Šªq–{ = 0xB;
			const int –¾’©’Ô–{ = 0xC;
			const int …–n‰æ = 0xD;
			const int “ì”ØŒv = 0xE;
			const int ’n‹…‹V = 0xF;
			const int ‰Œ‘ = 0x10;
			const int ƒr[ƒhƒ”t = 0x11;
			const int \š‰Ë = 0x12;
			const int ‹Êè”  = 0x13;
			const int ‰“Šá‹¾ = 0x14;
			const int –Ø = 0x15;
		};

		namespace ‰Æ•ó”z—ñ”Ô† {
			const int Â¥”nå›ãJ = 0;
			const int Â¥¼–{ = 1;
			const int •Šy‘å• = 2;
			const int ÔŠy‘‘D = 3;
			const int ŠD”íìŒõ“V–Ú = 4;
			const int ”’Šy•s“ñR = 5;
			const int ÂˆäŒËÄ“c = 6;
			const int —j•Ïˆî—t“V–Ú = 7;
			const int ŠGu–ì‰K‰ÔšÔ = 8;
			const int Ğ‰¨”’“V–Ú = 9;
			const int ‘åˆäŒË‰Á‰ê = 10;
			const int ÔŠyá•ô = 11;
			const int “‚•¨O“úŒ = 12;
			const int “‚•¨¼“‡ = 13;
			const int l\Î = 14;
			const int ¼‰Ô = 15;
			const int ‹´—§ = 16;
			const int ‹ã\‹ã”¯‰Öq = 17;
			const int ìŒõ¬‰Öq = 18;
			const int “‚•¨‰‰ÔŒ¨Õ = 19;
			const int “‚•¨“èÄŒ¨Õ = 20;
			const int “‚•¨V“cŒ¨Õ = 21;
			const int “‚•¨¼‰®Œ¨Õ = 22;
			const int “‚•¨•xm‰Öq = 23;
			const int “‚•¨Ğ‰¨‰Öq = 24;
			const int “‚•¨¨‚Œ¨Õ = 25;
			const int “‚•¨’©‘q•¶—Ô = 26;
			const int “‚•¨‰~ÀŒ¨Õ = 27;
			const int “‚•¨‹Ê“°Œ¨Õ = 28;
			const int “‚•¨ìŒõ•¶—Ô = 29;
			const int ‘i‰Öq = 30;
			const int ‘å—F•Z’\ = 31;
			const int “‚•¨“à“Ü‘åŠC = 32;
			const int —‚½‚è‰Öq = 33;
			const int ²”ŒŒ¨Õ = 34;
			const int ŒÃ“V–¾•½’wå = 35;
			const int èÅ‰WŒûŠÛŠ˜ = 36;
			const int Ä“›Š˜ = 37;
			const int ˆ°‰®^Œ` = 38;
			const int Â¥•“–³‚µ = 39;
			const int ’|ˆêd‰~é› = 40;
			const int Â¥‘å“à“› = 41;
			const int ŒÃ“º’ßˆêº = 42;
			const int ’|“ñd–é’· = 43;
			const int ‰©£ŒË—·– = 44;
			const int ‹SŠÛ = 45;
			const int ‹gŒõœ‹ò = 46;
			const int @O¶•¶š = 47;
			const int ‘º³ = 48;
			const int ŠÖ‚Ì‘·˜Z = 49;
			const int ˜aòçŒ“’è = 50;
			const int ˆ³Ø = 51;
			const int ‰ZÀŒ• = 52;
			const int ‰eG = 53;
			const int ‰úñ“ = 54;
			const int ¯Œ–é³@ = 55;
			const int —‹Ø = 56;
			const int “V‘ = 57;
			const int ’|–“Œ“Œõ = 58;
			const int ”õ‘O’·‘DŒ“Œõ = 59;
			const int å‘åxØ = 60;
			const int “ú–{† = 61;
			const int •ĞŠ™‘„ = 62;
			const int \•¶š‘„ = 63;
			const int ‘òàb‘„ = 64;
			const int •½“hŒÜ–‡“· = 65;
			const int ‹à¬DFXˆĞ = 66;
			const int ‹à‘É”ü‹ï‘« = 67;
			const int ‰ÔF“ú‚ÌŠÛˆĞ = 68;
			const int àçƒ‘fŒœˆĞ = 69;
			const int ”’…‘fŒœˆĞ = 70;
			const int g…ˆĞ¬• Šª = 71;
			const int ã|…‰ºUgˆĞ = 72;
			const int ¸’òq“ñ–‡“· = 73;
			const int “ì”Ø“·‹ï‘« = 74;
			const int ¼•— = 75;
			const int ’éßŒI–Ñ = 76;
			const int •ú¶Œ–Ñ = 77;
			const int •‰_ = 78;
			const int ¯è = 79;
			const int …‹Êw”nD = 80;
			const int ˆîÈŒ^ªŠGˆÆ = 81;
			const int ‹àæEw”nD = 82;
			const int ˆ°•äªŠGˆÆ = 83;
			const int ˆáŠ™–äw”nD = 84;
			const int Œ¹•¨Œê = 85;
			const int ˆÉ¨•¨Œê = 86;
			const int ŒÃ¡˜a‰ÌW = 87;
			const int •½‰Æ•¨Œê = 88;
			const int ‘¾•½‹L = 89;
			const int ŒÃ–‹L = 90;
			const int ‘·q = 91;
			const int ˜Zèé = 92;
			const int ‰©ÎŒöO—ª = 93;
			const int Oš u‰‰‹` = 94;
			const int j‹L = 95;
			const int …Ÿõ“` = 96;
			const int _‹È = 97;
			const int “Œ•ûŒ©•·˜^ = 98;
			const int ˆÉ‘\•Û•¨Œê = 99;
			const int —–šø‘Ò = 100;
			const int ’n‹…‹V = 101;
			const int ’uŒv = 102;
			const int ©–Âà = 103;
			const int “”µ} = 104;
			const int ànÃ–é‰J} = 105;
			const int “´’ëHŒ} = 106;
			const int ‰Œ›”Óà} = 107;
			const int ‰“‰Y‹A”¿} = 108;
			const int RsÂ—’} = 109;
			const int ‹™‘º—[Æ} = 110;
			const int •½¹—Šå} = 111;
			const int ]“V•éá} = 112;
			const int \š‰Ë = 113;
			const int ¹‘ = 114;
			const int ‹Êè”  = 115;
			const int ƒr[ƒhƒ”t = 116;
			const int ‰“Šá‹¾ = 117;
			const int ƒ‹ƒ\ƒ“šâ = 118;
			const int ƒ^ƒoƒR = 119;
		};

	}
}

using namespace —ñ‹“::‰Æ•ó;